-- SVConfig.FlashClient = true

-- SVConfig.UseDiscordLogging = true
-- WHConfig = { -- Fill this out if you want to use discord logging
--     webhook = "https://discord.com/api/webhooks/1136371932053373080/v5stLvkunk1rmQb2pDNa9C9p9BB7YAP4d32ourl4ZkmFnhrTqxXPgwsg9iQJLSszjzBK",
--     image = "https://i.imgur.com/soIsgMS.jpg",
--     name = "Automatic Camera Activation"
-- }

-- function CreateDiscordLogSpeed(source, camera, speed, plate, location, heading)
--     local webhook = WHConfig.webhook
--     local name = GetPlayerName(source)
--     local date = os.date('*t')
--     local time = os.date("*t")
--     local embedsetup = {
--         ["fields"] = {
--             {
--                 ["name"] = "Player Name: ",
--                 ["value"] = name,
--                 ["inline"] = true
--             },
--             {
--                 ["name"] = "Location: ",
--                 ["value"] = camera,
--                 ["inline"] = true
--             },
--             {
--                 ["name"] = "Speed Limit: ",
--                 ["value"] = camera.limit,
--                 ["inline"] = true
--             },
--             {
--                 ["name"] = "Detected Speed: ",
--                 ["value"] = speed,
--                 ["inline"] = true
--             },
--             {
--                 ["name"] = "License Plate:",
--                 ["value"] = plate,
--                 ["inline"] = true
--             },
--             {
--                 ["name"] = "Location:",
--                 ["value"] = location,
--                 ["inline"] = true
--             },
--             {
--                 ["name"] = "Heading:",
--                 ["value"] = heading,
--                 ["inline"] = true
--             },
--         },
--         ["color"] = 16767002,
--         ["title"] = "Automatic Camera Activation",
--         ["description"] = "",
--         ["footer"] = {
--             ["text"] = "Timestamp:"..os.date("%A, %m %B %Y | "), ("%02d:%02d:%02d"):format(time.hour, time.min, time.sec),
--         },
--         ["thumbnail"] = {
--             ["url"] = WHConfig.image,
--         },
--     }
--     print("Created Embed")
--     PerformHttpRequest(webhook, function(err, text, headers) end, 'POST', json.encode({ username = WHConfig.name, embeds = embedsetup }), { ['Content-Type'] = 'application/json' })
--     print("Sent Embed")
-- end

-- function CreateDiscordLogBOLO(source, camera, speed, plate, location, heading)
--     local webhook = WHConfig.webhook
--     local name = GetPlayerName(source)
--     local date = os.date('*t')
--     local time = os.date("*t")
--     local embedsetup = {
--         ["fields"] = {
--             {
--                 ["name"] = "Player Name: ",
--                 ["value"] = name,
--                 ["inline"] = true
--             },
--             {
--                 ["name"] = "Location: ",
--                 ["value"] = camera,
--                 ["inline"] = true
--             },
--             {
--                 ["name"] = "Speed Limit: ",
--                 ["value"] = camera.limit,
--                 ["inline"] = true
--             },
--             {
--                 ["name"] = "Detected Speed: ",
--                 ["value"] = speed,
--                 ["inline"] = true
--             },
--             {
--                 ["name"] = "License Plate:",
--                 ["value"] = plate,
--                 ["inline"] = true
--             },
--             {
--                 ["name"] = "Location:",
--                 ["value"] = location,
--                 ["inline"] = true
--             },
--             {
--                 ["name"] = "Heading:",
--                 ["value"] = heading,
--                 ["inline"] = true
--             },
--         },
--         ["color"] = 16777215,
--         ["title"] = "Automatic Camera Activation",
--         ["description"] = "",
--         ["footer"] = {
--             ["text"] = "Timestamp:"..os.date("%A, %m %B %Y | "), ("%02d:%02d:%02d"):format(time.hour, time.min, time.sec),
--         },
--         ["thumbnail"] = {
--             ["url"] = WHConfig.image,
--         },
--     }
--     print("Created Embed")
--     PerformHttpRequest(webhook, function(err, text, headers) end, 'POST', json.encode({ username = WHConfig.name, embeds = embedsetup }), { ['Content-Type'] = 'application/json' })
--     print("Sent Embed")
-- end